// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTh8Ln5HrwTwkcyhtH0iKPa3JLQfOTetM',
    appId: '1:421426117703:web:47d56f1a8e1bc3a8bc0562',
    messagingSenderId: '421426117703',
    projectId: 'paychatkoli',
    authDomain: 'paychatkoli.firebaseapp.com',
    storageBucket: 'paychatkoli.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyrUDNf1Uwe0b6IhxtiY1BFkRQ7jLHSJE',
    appId: '1:421426117703:android:5b809a4e86a6e700bc0562',
    messagingSenderId: '421426117703',
    projectId: 'paychatkoli',
    storageBucket: 'paychatkoli.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEe-R90jDBAd1HiINXzsNYfnybU30YxY8',
    appId: '1:421426117703:ios:a57ab5197257c3f3bc0562',
    messagingSenderId: '421426117703',
    projectId: 'paychatkoli',
    storageBucket: 'paychatkoli.firebasestorage.app',
    iosBundleId: 'com.paychat.paychat',
  );
}
